version: '3'

networks: 
  ens-test:
    driver: bridge

services: 

  #application
  laravel-test-app: 
          build:
            context: .
            dockerfile: Dockerfile
          container_name: devops-assignment-app
          restart: unless-stopped
          ports: 
            - 8090:8090
          volumes: 
            - ./:/var/wwww
          command: "php artisan serve --host=0.0.0.0 --port=8090"
          depends_on: 
            - db
            - redis
          networks: 
            - ens-test
  
  #database
  db:
    image: mysql:5.7.33
    container_name: mysql3
    restart: unless-stopped
    tty: true
    ports: 
      - 3310:3310
    volumes: 
      - ./mysql3:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: devops_assignment
      MYSQL_USER: devops_assignment
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks: 
      - ens-test

  #redis
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - 6390:6379
    networks: 
      - ens-test

  #nginx
  web:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports: 
      - 8081:80
    volumes: 
      - ./:/var/www
      - ./vhost.conf:/etc/nginx/host.conf
    networks: 
      - ens-test